apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: gl3o81g6r-python-gitops
  description: This is GitOps manifest for gl3o81g6r-python   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-name: gl3o81g6r-python
    backstage.io/kubernetes-id: gl3o81g6r-python 
    backstage.io/techdocs-ref: dir:. 
    janus-idp.io/tekton: gl3o81g6r-python   
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:gl3o81g6r-python
